name: Linting

on:
  push:
    branches: [ suma/4.3, suma/head, uyuni/master ]
  pull_request:
    branches: [ suma/4.3, suma/head, uyuni/master ]

jobs:
  lint_docs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 #v5.5.0
      with:
        python-version: 3.9
    - name: Install dependencies
      run:  pip install -U "rstcheck<6" doc8
    - name: Run rstcheck
      run:  rstcheck -r docs
    - name: Run doc8
      run: doc8 --ignore D001 docs
  lint_shellscripts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 #v2.0.0
        with:
          scandir: './scripts'
